### ISSUE TITLE
Use it without owl-items repeat

### ISSUE THREAD

**Issue by arthurhamon** [DjKarui/angular-owl-carousel-directive#2]
How to implement the directive without owl-items repeat directive ?

I want this to work with manual items set like this

`<div class="owl-theme" owl-carousel owl-options="vm.owlOptions">
        <div class="owl-item"></div>
        <div class="owl-item"></div>
        <div class="owl-item"></div>
     </div>`

**Comment by DjKarui** [comment]
hey
`owl-items` is an attribute used to generate the carousel items, it not another directive

  ```
<div class="owl-theme" owl-carousel owl-items="vm.owlItems" owl-options="vm.owlOptions">
        <div class="owl-item">{{ index }} - {{ item }}</div>
</div>
```

**Comment by arthurhamon** [comment]
Yes, but how use it without the ng-repeat ?

**Comment by DjKarui** [comment]
The directive is not meant for this kind of functionality. You can enable the Owl Carousel without this directive if is an static slider. Use `$(element).owlCarousel(options);` in your controller if you need to use AngularJS for this.
